;
; File generated by cc65 v 2.19 - Git 3d7e388
;
	.fopt		compiler,"cc65 v 2.19 - Git 3d7e388"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ wait_vblank (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_wait_vblank: near

.segment	"CODE"

L0008:	lda     $2002
	and     #$80
	bne     L0008
L0009:	lda     $2002
	and     #$80
	beq     L0009
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ ppu_write16 (unsigned int addr, unsigned char value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ppu_write16: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	sta     $2006
	dey
	lda     (c_sp),y
	sta     $2006
	dey
	lda     (c_sp),y
	sta     $2007
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	lda     #$00
	sta     $2005
	sta     $2005
	lda     #$80
	sta     $2000
	lda     #$1E
	sta     $2001
	lda     #$00
	tay
L0007:	sta     (c_sp),y
L0005:	jsr     _wait_vblank
	ldx     #$3F
	lda     #$00
	jsr     pushax
	ldy     #$02
	lda     (c_sp),y
	jsr     _ppu_write16
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	cmp     #$40
	bcc     L0005
	tya
	jmp     L0007

.endproc

